### PR TITLE
Statsupdate

### PR DESCRIPTION
**Pull request by carterm**

### CODE REVIEW

**Comment by carterm** [comment]
(Added SNOWFLAKE_USER/PASS) to Azure settings.

**Review by aaronhans — APPROVED** [review]
good stuff Carter!

**Comment by aaronhans** [comment]
How is this triggered?

**Comment by carterm** [comment]
How is this triggered? ... It's checking on every run for the existence of a PR that matches today's date.  If the PR isn't there, it makes it.

**Pull request merged**
